version: '3'
services:
    database:
        image: mysql
        container_name: database
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: sprig-client-crud
            MYSQL_USER: root
            MYSQL_PASSWORD: 1234

    backend:
        build: ./backend
        container_name: backend
        environment:
            - MYSQL_DATABASE=sprig-client-crud
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=1234
        ports:
            - 8080:8080
        links:
            - database
        depends_on:
            - database

    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - 4200:80
        links:
            - backend
